accounts/urls.py
from django.urls import path

from . import views
from django.contrib.auth import views as auth_views

app_name='accounts'

urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('signup_success/', views.SignUpSuccessView.as_view(), name='signup_success'),

    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),        
]

comment/urls.py
from django.urls import path
from . import views

app_name='comment'

urlpatterns = [
    path('comments/<int:post_id>', views.CommentListView.as_view(), name='comment_list'),
    path('comment_post/<int:post_id>', views.CerateCommentView.as_view(), name='comment_post'),
    path('comment_post_done/', views.CommentSuccessView.as_view(), name='comment_done')
]

print/urls.py
from django.urls import path
from . import views

app_name='print'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    
    path('post/', views.CreatePaintView.as_view(), name='post'),
    path('post_done/', views.PostSuccessView.as_view(), name='prin_post_done'),
    path('posts/<int:category>', views.CategoryView.as_view(), name='prints_cat'),
    path('user-list/<int:user>', views.UserView.as_view(), name='user_list'),
    path('paint-detail/<int:pk>', views.DetailView.as_view(), name='print_detail'),
    path('mypage/', views.MypageView.as_view(), name='mypage'),
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('paint/<int:pk>/delete/', views.PostDeleteView.as_view(), name='post_delete'),        
]

test2_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    
    # 追加したURL
    path('', include('print.urls')),
    path('', include('accounts.urls')),  
    path('', include('comment.urls')),   
]

print/models.py
from django.db import models

from accounts.models import CustomUser
# Create your models here.

class Category(models.Model):
    '''投稿する画像のカテゴリを管理するモデル'''
    # カテゴリ名のフィールド
    title=models.CharField(
        verbose_name='カテゴリ', # フィールドのタイトル
        max_length=15
        )
    
    def __str__(self):
        '''オブジェクトを文字列に変換して返す'''
        return self.title

class PaintPost(models.Model):
    '''投稿されたデータを管理するモデル'''
    
    # CustomUserモデル(のuser_id)とPaintPostモデルを1対多の関係で結びつける。
    user= models.ForeignKey(
        CustomUser,
        verbose_name='ユーザー', # フィールドのタイトル
        on_delete=models.CASCADE # ユーザーを削除する場合はそのユーザの投稿データも全て削除
    )
    
    # Categoryモデル(のtitle)とPaintPostモデルを1対多の関係で結びつける。
    category=models.ForeignKey(
        Category,
        verbose_name='カテゴリ', # フィールドのタイトル
        on_delete=models.PROTECT # カテゴリに関連付いたデータがあるならカテゴリを削除できない
    )
    
    # タイトル用フィールド
    title=models.CharField(
        verbose_name='タイトル', # フィールドのタイトル
        max_length=50 # 最大文字数50
    )
    
    # コメント用フィールド
    comment=models.TextField(
        verbose_name='コメント', # フィールドのタイトル
        max_length=500 # 最大文字数500
    )
    
    # 画像を文字列で投稿するためのテキストフィールド
    image=models.TextField(
        verbose_name='イラスト', # フィールドのタイトル
    )
    
    # 投稿日時のフィールド
    posted_at=models.DateTimeField(
        verbose_name='投稿日時', # フィールドのタイトル
        auto_now_add=True # 日時を自動追加
    )
    
    def __str__(self):
        '''オブジェクトを文字列にして返す'''
        return self.title
    

print/forms.py
from django.forms import ModelForm
from django import forms
from .models import PaintPost

class PaintPostForm(ModelForm):
    '''ModelFormのサブクラス'''
    class Meta:
        '''ModelFormのインナークラス'''
        model=PaintPost
        fields=['category','title','comment','image']


class ContactForm(forms.Form):
    # フォームのフィールドをクラス変数として定義
    name=forms.CharField(label='　　　　お名前')
    email=forms.EmailField(label='メールアドレス')
    title=forms.CharField(label='　　　　　件名')
    message=forms.CharField(label='　　メッセージ', widget=forms.Textarea)
    
    def __init__(self, *args, **kwargs):
        '''ContactFormのコンストラクタ
        フィールドの初期化を行う
        '''
        super().__init__(*args, **kwargs)
        # nameフィールド
        self.fields['name'].widget.attrs['placeholder']=\
            'お名前を入力してください'
        self.fields['name'].widget.attrs['class']='form-control'
        
        # emailフィールド
        self.fields['email'].widget.attrs['placeholder']=\
            'メールアドレスを入力してください'
        self.fields['email'].widget.attrs['class']='form-control'            
            
        # titleフィールド
        self.fields['title'].widget.attrs['placeholder']=\
            'タイトルを入力してください'
        self.fields['title'].widget.attrs['class']='form-control'             
            
        # messageフィールド
        self.fields['message'].widget.attrs['placeholder']=\
            'メッセージを入力してください'
        self.fields['message'].widget.attrs['class']='form-control'

print/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render

from django.views.generic import TemplateView, ListView, FormView
from django.views.generic import CreateView
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.views.generic import DetailView
from django.contrib import messages
from django.core.mail import EmailMessage
from django.views.generic import DeleteView

from .forms import PaintPostForm
from .models import PaintPost
from .forms import ContactForm
# Create your views here.



class IndexView(ListView):
    '''トップページのビュー'''
    template_name='index.html'
    # order_by()を適用して投稿日時の降順で並び替える
    queryset=PaintPost.objects.order_by('-posted_at')
    # 1ページの表示件数
    paginate_by=12
    
    
# デコレーターにより、CreatePhotoViewへのアクセスはログインユーザーに限定される
# ログイン状態でなければsettings.pyのLOGIN_URLにリダイレクトされる
@method_decorator(login_required, name='dispatch')

class CreatePaintView(CreateView):
    '''イラストページのビュー
    PhotoPostFormで定義されているモデルとフィールドと連携して投稿データをデータベースに登録する'''
    form_class=PaintPostForm
    template_name="print_post.html"
    success_url=reverse_lazy('print:prin_post_done')
    
    def form_valid(self, form):
        '''CreateViewクラスのform_valid()をオーバーライド
        
        フォームのバリデーションを通過したときに呼ばれる
        フォームデータの登録をここで行う'''
        # commit=FalseにしてPOSTされたデータを取得
        postdata=form.save(commit=False)
        # 投稿ユーザのidを取得してモデルのuserフィールドに格納
        postdata.user=self.request.user
        # 投稿データをデータベースに登録
        postdata.save()
        return super().form_valid(form)

class PostSuccessView(TemplateView):
    '''投稿完了ページのビュー'''
    template_name='prin_post_success.html'
    

class CategoryView(ListView):
    '''カテゴリの投稿一覧ページのビュー'''
    template_name='index.html'
    paginate_by=12
    
    def get_queryset(self):
        '''クエリを実行'''
        category_id=self.kwargs['category']
        categories=PaintPost.objects.filter(category=category_id).order_by('-posted_at')
        return categories

class UserView(ListView):
    '''ユーザーの投稿一覧のビュー'''
    template_name='index.html'
    paginate_by=12
    def get_queryset(self):
        '''クエリを実行'''
        user_id=self.kwargs['user']
        user_list=PaintPost.objects.filter(user=user_id).order_by('-posted_at')
        return user_list

class DetailView(DetailView):
    '''詳細ページのビュー'''
    template_name='detail.html'
    model=PaintPost
    context_object_name = 'record'

class MypageView(ListView):
    '''マイページのビュー'''
    template_name="mypage.html"
    paginate_by=12
    def get_queryset(self):
        '''クエリを実行する'''
        queryset=PaintPost.objects.filter(user=self.request.user).order_by('-posted_at')
        return queryset

class ContactView(FormView):
    '''お問い合わせページのビュー'''
    template_name='contact.html'
    form_class=ContactForm
    success_url=reverse_lazy('print:contact')
    
    def form_valid(self, form):
        name=form.cleaned_data['name']
        email=form.cleaned_data['email']
        title=form.cleaned_data['title']
        message=form.cleaned_data['message']
        subject='お問い合わせ:{}'.format(title)
        message = \
            '送信者名: {0}\nメールアドレス: {1}\n タイトル:{2}\n メッセージ：\n{3}'.format(name, email, title, message)
        # メールの送信元のアドレス
        from_email = 'tky2302040@stu.o-hara.ac.jp'
        # 送信先のメールアドレス
        to_list = ['tky2302040@stu.o-hara.ac.jp']
        message=EmailMessage(subject=subject,
                               body=message,
                               from_email=from_email,
                               to=to_list,
                               )
        message.send()
        messages.success(
            self.request, 'お問い合わせは正常に送信されました。'
        )
        return super().form_valid(form)

class PostDeleteView(DeleteView):
    '''レコードの削除を行う'''
    model=PaintPost
    template_name='post_delete.html'
    success_url=reverse_lazy('print:mypage')
    
    def delete(self, request, *args, **kwargs):
        '''レコードの削除を行う'''
        return super().delete(request, *args, **kwargs)
            

print/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="utf-8">
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href={% static "print_css/base_css.css" %}>
        <link rel="icon" type="image/x-icon" href="{% static "print_img/favicon.ico" %}">
        <script defer src='https://nadesi.com/v3/cdn.php?v=3.4.21&f=release/wnako3.js&run'></script>
        <script defer src='https://nadesi.com/v3/cdn.php?v=3.4.21&f=release/plugin_csv.js'></script>
        <script defer src='https://nadesi.com/v3/cdn.php?v=3.4.21&f=release/plugin_datetime.js'></script>
        <script defer src='https://nadesi.com/v3/cdn.php?v=3.4.21&f=release/plugin_markup.js'></script>
        <script defer src='https://nadesi.com/v3/cdn.php?v=3.4.21&f=release/plugin_kansuji.js'></script>
        <script defer src='https://nadesi.com/v3/cdn.php?v=3.4.21&f=release/plugin_turtle.js'></script>
    </head>

    <body>

        <div id="outer">
            <header>
                <a href="{% url 'print:index' %}" style="text-decoration: none;"> 
                <h1>{% block title2 %}{% endblock %}</h1>
                </a>
                <p>{% block description %}{% endblock %}</p>
            </header>
            <hr style="background-color: #6CA4D1;">

            
            <main>
                {% block contents %}{% endblock %}
            </main>

            <footer>
                {% include "pagination.html" %}
                <br><br><br>
                © 2023 単位認定試験
            </footer>
        </div>

    </body>
</html>

print/templates/contact.html
{% extends "base.html" %}
{% load static %}
<!--=================================================================-->
{% block title %}極小画廊_お問い合わせ{% endblock %}
{% block title2 %}極小画廊{% endblock %}
{% block description %}お問い合わせ{% endblock %}
<!--=================================================================-->
{% block contents %}

<div style="width: 50%; margin: 0 auto; text-align: center;">
    <strong>連絡を取る場合は以下のフォームからお願いします</strong>
    <br><br>
    <!--フォームの送信が成功した時のメッセージを表示するためのコード-->
    <!--requestにmessageオブジェクトが存在している場合-->
    {% if messages %}<!--viewsのmessages.successと対応している-->
    <ul style="list-style: none;">
        <!--forでmessage取り出す-->
        {% for message in messages %}
        <!--message.tagsが存在する場合はclass属性にCSSのクラスを設定-->
        <li {% if message.tags %} class="{{ message.tags }}" {% endif %} style="color:red;">
            {{ message }}
        </li>
        {% endfor %}
    </ul>
    {% endif %}

    <!--以下、フォーム表示-->
    <form method="post">
        {% csrf_token %}
        {% for field in form %}
            <div >
                {{ field.label_tag }}
                {{ field }}
            </div>
        {% endfor %}
        <br>
        <button type="submit" id="sendMessageButton">送信</button>
    </form>
</div>

{% endblock %}

print/templates/detail.html
{% extends "base.html" %} 
{% load static %}
<!--=================================================================-->
{% block title %}『{{ object.title }}』_極小画廊{% endblock %}
{% block title2 %}極小画廊{% endblock %}
{% block description %}詳細ページ{% endblock %}
<!--=================================================================-->
{% block contents %}

<div style="width: 50%; margin: 0 auto; text-align: center;">
    <br>
    <p font="font-size: 70%;">{{ object.posted_at }}に投稿</p>
    <a href="{% url "print:user_list" user=object.user.id %}">
        <p font="font-size: 70%;">投稿者：{{ object.user.username }}</p>
    </a>
    <br>
    <h1>『{{ object.title }}』</h1>
    <p><img src="{{ object.image }}"></P>
    <a href="{% url "print:prints_cat" category=object.category.id %}">
        <p font="font-size: 70%;">カテゴリ：{{ object.category.title }}</p>
    </a>
    <br>
    <p>{{ object.comment }}<p>
    <br>
    {% if user.is_authenticated %}
    <p><a href="{% url "comment:comment_post" post_id=record.pk %}">この作品へコメントする</a></p>
    <p><a href="{% url "comment:comment_list" post_id=record.pk %}">この作品へのコメントを見る</a></p>
    {% endif %}
    <br>
    <!--投稿写真がログイン中のユーザーのものであるか確認-->
    {% if request.user == object.user %}
    <form method="POST">
        <a href="{% url "print:post_delete" object.pk %}" style="color:red;">※削除する※</a> 
    {% endif %}
    <br><br><br>
</div>

{% endblock %}

print/templates/index.html
{% extends "base.html" %}
{% load static %}
<!--=================================================================-->
{% block title %}極小画廊_Home{% endblock %}
{% block title2 %}極小画廊{% endblock %}
{% block description %}ゆるくミニイラストを描けるサイト{% endblock %}
<!--=================================================================-->
{% block contents %}

{% include "print_posts.html" %}
{% include "print_side.html" %}
{% endblock %}

print/templates/mypage.html
{% extends "base.html" %}
{% load static %}
<!--=================================================================-->
{% block title %}極小画廊_マイページ{% endblock %}
{% block title2 %}極小画廊{% endblock %}
{% block description %}マイページ{% endblock %}
<!--=================================================================-->
{% block contents %}
{% if user.is_authenticated %}
<br>
<div style="text-align: center;">
    <h1>{{ user.username }} さんのマイページ</h1>
    {% if object_list.count == 0 %}
        <p>{{ user.username }}さんの投稿はありません。</p>
    {% else %}
        <p>投稿 <strong>{{ object_list.count }}</strong>件</p>
    {% endif %}
    <a href="{% url "print:post" %}">＞＞投稿する＜＜</a>
</div>
<hr style="background-color: #6CA4D1;">
{% endif %}

{% include "print_posts.html" %}
{% include "print_side.html" %}
{% endblock %}

print/templates/pagination.html
<!--ページネーションのアイコンを左右中央に表示-->
<ul class="pagination" style="justify-content:center; list-style:none; display: flex; flex-wrap: wrap; gap: 60px 1.4%;">
    <!--
        前ページを表示するアイコンとリンクの設定
        ページネーションされたPageオブジェクトをpage_objで取得
        Page.has_previous: 直前にページがある場合にTrueを返す
    -->
    {% if page_obj.has_previous %}
    <!--
        前ページが存在する場合はそのページへのリンクが設定されたアイコン[<<]を表示
        page.previous_page_number: 直前のページ番号を返す
    -->
    <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
        </a>
    </li>
    {% endif %}
    <!--
        すべてのページについてページ番号のアイコンを表示
        paginator.page_range: [1,2,3,4]のように1から始まるページ番号を返す
        page_obj.paginator.page_rangeとして取得
        ブロックパラメーターnumに順次取り出される
    -->
    {% for num in page_obj.paginator.page_range %}
        <!--
            各ページのアイコンを出力
            Page.number: 引き渡されたページのページ番号を返す
        -->
        {% if page_obj.number == num %}
        <!--
            処理中のページ番号が引き渡されたページのページ番号と一致する場合は
            ページ番号のアイコン(アクティブ状態)を表示(リンクは設定しない)
        -->
        <li class="page-item active">
            <span class="page-link">{{ num }}</span>
        </li>
        <!--
            ページ番号が引き渡されたページのページ番号と一致しない場合
        -->
        {% else %}
        <!--
            ページ番号のアイコン(アクティブ状態でない)にリンクを設定して表示
        -->
        <li class="page-item">
            <a class="page-link" href="?page={{ num }}">{{ num }}</a>
        </li>
        {% endif %}
    {% endfor %}
    <!--
        次ページへのリンクを示すアイコンの表示
        Page.has_next: 次ページがある場合にTrueを返す
    -->
    {% if page_obj.has_next %}
    <!--
        次ページが存在する場合はリンクを設定したアイコン[>>]を表示
        Page.next_number:次ページ番号を返す
    -->
    <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
        </a>
    </li>
    {% endif %}
</ul>
        

print/templates/post_delete.html
{% extends "base.html" %}
{% load static %}
<!--=================================================================-->
{% block title %}極小画廊_削除{% endblock %}
{% block title2 %}極小画廊{% endblock %}
{% block description %}投稿作品の削除{% endblock %}
<!--=================================================================-->
{% block contents %}
<br>
    <form method="POST" style="text-align: center;">
        <br>
        <p style="color:red;">削除してもよろしいですか？</p>
        {% csrf_token %}
        <button type="submit">削除</button>
        <br><br>
        <a href="{% url "print:print_detail" object.pk %}">＞＞キャンセルして戻る＜＜</a>
        <br><br>
{% endblock %}

print/templates/prin_post_success.html
{% extends "base.html" %}
{% load static %}
<!--=================================================================-->
{% block title %}極小画廊_投稿成功{% endblock %}
{% block title2 %}極小画廊{% endblock %}
{% block description %}完成{% endblock %}
<!--=================================================================-->
{% block contents %}
<div>
    <h1 style="text-align: center;">投稿が完了しました！</h1>
    <br><br><br><br>
    <p style="text-align: center;"><a href="{% url "print:index" %}">＞＞トップページへ＜＜</a></p>
    <br><br>
</div>
{% endblock %}

print/templates/print_post.html
{% extends "base.html" %}
{% load static %}
<!--=================================================================-->
{% block title %}極小画廊_投稿{% endblock %}
{% block title2 %}極小画廊{% endblock %}
{% block description %}気軽にどんな事柄でも描いてみましょう{% endblock %}
<!--=================================================================-->
    {% block contents %}
    <div style="width: 50%; margin: 0 auto; text-align: center;">
        <div class="paint_area">
            <br>
            <canvas class="paint_box" id="test_canvas" width=200 height=100 style="border: solid 3px #000000; float: left;"></canvas>
            <input type="button" id="pen1" value="極細モード">
            <input type="button" id="pen2" value="細モード">
            <input type="button" id="pen3" value="普通モード">
            <input type="button" id="pen4" value="太モード">
            <input type="button" id="pen5" value="極太モード">
            <br><br>
            <input type="color" id="color_changer" value="#FFC200">
            <input type="button" id="fill_button" value="全体塗りつぶし">
        </div>            
            <br>
            <input type="button" id="end_button" value="完成">
            <br>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <table>
                <tr>
                    <th >カテゴリ</th>
                    <td>{{ form.category }}</td>
                </tr>
                <tr>
                    <th>タイトル</th>
                    <td>{{ form.title }}</td>
                </tr>
                <tr>
                    <th>コメント</th>
                    <td>{{ form.comment }}</td>
                </tr>
                <tr hidden>
                    <th>イラスト</th>
                    <td>{{ form.image }}</td>
                </tr>
            </table>
            <p style="color: red;">「完成」ボタンをクリックしないと投稿されません。</P>
            <button type="submit">投稿する</button>
            <br><br>
        </form>
    </div>

    <script type="なでしこ">
        色変更ボタン＝「#color_button」のDOM要素取得。
        完成ボタン＝「#end_button」のDOM要素取得。
        塗りつぶしボタン＝「#fill_button」のDOM要素取得。
        ペン１ボタン＝「#pen1」のDOM要素取得。
        ペン２ボタン＝「#pen2」のDOM要素取得。
        ペン３ボタン＝「#pen3」のDOM要素取得。
        ペン４ボタン＝「#pen4」のDOM要素取得。
        ペン５ボタン＝「#pen5」のDOM要素取得。
        描画範囲＝「canvas#test_canvas」のDOM要素取得。
        描画範囲へ描画開始。
        
        現モード＝3
        クリックフラグ＝オフ。
        元ｘ＝０。元ｙ＝０。今ｘ＝０。今ｙ＝０。
        
        ペン１ボタンをクリックした時には、
        　　現モード＝0.7
        ここまで。
        
        ペン２ボタンをクリックした時には、
        　　現モード＝1.7
        ここまで。
        
        ペン３ボタンをクリックした時には、
        　　現モード＝3
        ここまで。
        
        ペン４ボタンをクリックした時には、
        　　現モード＝6
        ここまで。
        
        ペン５ボタンをクリックした時には、
        　　現モード＝10
        ここまで。
        
        #-------------
        描画中キャンバスをマウス押した時には、
        　　色設定＝「#color_changer」の「value」をDOM属性取得。
        　　「｛色設定｝」に塗色設定。
        　　「｛色設定｝」に線色設定。
        　　クリックフラグ＝オン。元ｘ＝マウスX。元ｙ＝マウスY。
        ここまで。
        
        描画中キャンバスをマウス移動した時には、
        　　もし、クリックフラグがオフならば、戻る。
        　　色設定＝「#color_changer」の「value」をDOM属性取得。
        　　「｛色設定｝」に塗色設定。
        　　「｛色設定｝」に線色設定。
        　　今ｘ＝マウスX。今ｙ＝マウスY。絵描。
        　　もし、現モードが4以下ならば、戻る。
        　　　　[今ｘ,今ｙ]へ現モード/2-2の円描画。
        ここまで。
        
        描画中キャンバスをマウス離した時には、
        　　クリックフラグ＝オフ。
        ここまで。
        
        ●絵描
        　　現モードに線太設定。
        　　[元ｘ,元ｙ]から[今ｘ,今ｙ]へ線描画。
        　　元ｘ＝今ｘ。元ｙ＝今ｙ。
        ここまで。
        #-------------
        
        塗りつぶしボタンをクリックした時には、
        　　色設定＝「#color_changer」の「value」をDOM属性取得。
        　　「｛色設定｝」に塗色設定。
        　　「｛色設定｝」に線色設定。
        　　[0, 0, 200, 100]へ四角描画。
        ここまで。
        
        完成ボタンをクリックした時には、
        　　取得画像＝描画データURL変換。
        　　「#id_image」に、「｛取得画像｝」をテキスト設定
        ここまで。
    </script> <!--なでしこ参考ページ:https://nadesi.com/v3/doc/index.php?plugin_browser&show-->
    {% endblock %}

print/templates/print_posts.html
{% load static %}
<section id="content">
    <div class="inner"><h2>作品一覧</h2>
        <ul class="postList">
          {% for record in object_list %}
            <li>
             <a href="{% url "print:print_detail" record.pk %}">
               <figure class="pic">
                 <img src="{{ record.image }}">
               </figure>
              </a>
              <div>
                <a href="{% url "print:prints_cat" category=record.category.id %}">
                  <p style="margin-top: 0px; margin-bottom: 3px; font-size: 50%; text-align: center;">{{ record.category.title }}</p>
                </a>
                <p style="margin-top: 0px; margin-bottom: 3px; font-size: 70%; text-align: center;">『{{ record.title }}』</p>
              </div>
            </li>
            {% endfor %}
      </div>
</section>

print/templates/print_side.html
{% load static %}
<aside>
    <div class="right-title">メニュー</div>
    <div class="link">
        <ul>
            <li><a href="{% url "print:index" %}">トップページ</a></li>
            <li><a href="{% url "print:contact" %}">お問い合わせ</a></li>
            {% if user.is_authenticated %}
            <!--ログイン中のメニュー-->
            <li><a href="{% url "print:post" %}">絵を描く</a></li>            
            <li><a href="{% url "print:mypage" %}">マイページ</a></li>
            <li><a href="{% url "accounts:logout" %}">ログアウト</a></li>
            {% else %}
            <!--非ログイン状態のメニュー-->  
            <li><a href="{% url "accounts:login" %}">ログイン</a></li>          
            <li><a href="{% url "accounts:signup" %}">新規アカウント登録</a></li>
            {% endif %}
        </ul>
    </div>
</aside>